### ISSUE TITLE
Integrate CVE ID assignment, generation, and submission/publication

### ISSUE THREAD

**Issue by zmanion** [CERTCC/VINCE#11]
Integrate with emerging CVE services: https://github.com/CVEProject/cve-services

Reserve/assign CVE IDs to vulnerabilities (not cases)
Manage a pool of CVE IDs (if that is still a thing)
Collect and produce valid CVE JSON (mostly done)
Submit CVE IDs/JSON to the right place (github now, a new service at some point)
Store necessary CVE user/organizational account information? (API key? other credentials?)

**Comment by santosomar** [comment]
I like this enhancement request. This could help the process of vendor statements immensely, since each of the vendor statement/security advisories could be immediately linked under the references and other constructs of the [CVE JSON file](https://github.com/CVEProject/automation-working-group/tree/master/cve_json_schema)

**Comment by zmanion** [comment]
Production VINCE supports reservation and content creation, submission is coming soon, waiting for the CVE Program to enable it first.

**Comment by Daniel-INL** [comment]
@sei-vsarvepalli I wanted to breath new life in this as CVE Services 2.1 is now operational. Does CERT/CC plan to include their 2.1 implementation in VINCE? https://certcc.github.io/cveClient/

**Comment by sei-vsarvepalli** [comment]
> @sei-vsarvepalli I wanted to breath new life in this as CVE Services 2.1 is now operational. Does CERT/CC plan to include their 2.1 implementation in VINCE? https://certcc.github.io/cveClient/ I believe the current JSON export for CVE data will need to be corrected as it does not output valid CVE JSON as per Vulnogram validator.

@Daniel-INL 

VINCE already has CVE services integration from a server-side instead of the JavaScript client based cveClient.   The CVEServicesDashboard View (see code segment below), which has all the capability to do CVE assignment and integration with CVE services 2.1 using RedHat PSIRT's cvelib server-side.  It has been tested a few times, (has a few small bugs to fix) but  CVE reservation, basic CVE JSON generation and CVE publishing via RSUS interface are all tested to work well. The benefit of the server-side is the API Key's can be stored on the server, if that is considered private. However cvelib itself does not create a CVE 5 JSON for you, it only provides CVE Services client.

The JavaScript cveClient project itself was written primarily for CNA's who are looking for a hosted solution for CVE Management (create, publish, update CVE's/Users in one place) instead of integration with their PSIRT ticketing system. The cveClient itself works right with the CVE Service 2.1 and CVE 5 JSON with minimal information needed according to CVE 5 JSON schema.  Vulnogram includes additional fields which we (CERT/CC) currently decided not to enforce as requirements for a CVE 5 JSON setup (for e.g., problemTypes is one such field).  

https://github.com/CERTCC/VINCE/blob/213dcd9762798a8f279e10d252d1ba4d9e6f0ce4/vince/views.py#L14610

https://github.com/RedHatProductSecurity/cvelib

**Comment by z-priest** [comment]
@sei-vsarvepalli 

The ability to publish directly from VINCE using reserved CVE-IDs is desired. If this is implemented, can you point me to where? I poked around some and couldn't find this functionality currently built in. From original issue creation back in May, Submit CVE IDs/JSON line mentions a new service at some point.

A solution could be bumping cvelib from 0.7.0 to 1.0.0 and utilizing the new publish function?
https://github.com/RedHatProductSecurity/cvelib/compare/0.7.0...1.0.0

I figure since cvelib is already used to reserve a set of IDs, show reserved IDs and grab cve_lists from MITRE via API, it would also be valid to use to publish through.

One impact is cve_lib.show_cve function has been renamed/reworked to either show_cve_record or show_cve_id

**Comment by sei-vsarvepalli** [comment]
> @sei-vsarvepalli
> 
> The ability to publish directly from VINCE using reserved CVE-IDs is desired. If this is implemented, can you point me to where? I poked around some and couldn't find this functionality currently built in. From original issue creation back in May, Submit CVE IDs/JSON line mentions a new service at some point.
> 
> A solution could be bumping cvelib from 0.7.0 to 1.0.0 and utilizing the new publish function? [RedHatProductSecurity/cvelib@0.7.0...1.0.0](https://github.com/RedHatProductSecurity/cvelib/compare/0.7.0...1.0.0)
> 
> I figure since cvelib is already used to reserve a set of IDs, show reserved IDs and grab cve_lists from MITRE via API, it would also be valid to use to publish through.
> 
> One impact is cve_lib.show_cve function has been renamed/reworked to either show_cve_record or show_cve_id

Hello Zach,

The CVE management is under URL http://localhost:8000/vince/manage/cve/ for a local running instance or you can reach it in a working VINCETrack local application under drop down on the right corner to menu "User Admin" -> "CVE Services" -> "+ Add CVE Account" 

The cvelib needs change and be upgraded to cve-2.1 services which is actually at https://github.com/RedHatProductSecurity/cvelib/compare/0.7.0...cve-services-2.1.0 . I don't think RedHat has pushed it out yet, but it is in the cve-services-2.1 branch for fully functional services to CVE 2.1 RSUS interface to both manage CVE assignments as well as user assignment.  We will be moving to the 2.1.0 library once all is fully functional in our development instance. The feature that is missing is update CVE for an already public CVE in the cvelib API. All that is targeted for Early December release once all CVE 5 and CVE-services-2.1 are stable.

Thanks
Vijay

**Comment by z-priest** [comment]
Thanks for clarification here!
